

```{r}
library(tidyverse)

move_one_step <- function(head_tail_list, dir) {
  n <- length(head_tail_list)
  for (i in seq_along(head_tail_list)[-n]) {
    # Get coordinates of current head-tail-pair
    head_x <- head_tail_list[[i]]$x[length(head_tail_list[[i]]$x)]
    head_y <- head_tail_list[[i]]$y[length(head_tail_list[[i]]$y)]
    tail_x <- head_tail_list[[i + 1]]$x[length(head_tail_list[[i + 1]]$x)]
    tail_y <- head_tail_list[[i + 1]]$y[length(head_tail_list[[i + 1]]$y)]
    
    # Move only head manually - rest should be reaction to other movement
    if (i == 1) {
      head_x <- head_x + (dir == 'R') - (dir == 'L')
      head_y <- head_y + (dir == 'U') - (dir == 'D')
      head_tail_list[[i]]$x <- append(head_tail_list[[i]]$x, head_x)
      head_tail_list[[i]]$y <- append(head_tail_list[[i]]$y, head_y)
    }
    
    # Compute new coordinate of current tail element
    if (abs(head_x - tail_x) > 1 & (head_y == tail_y)) {
      tail_x <- tail_x + ((head_x - tail_x) > 0) - ((head_x - tail_x) < 0)
    } else if (abs(head_y - tail_y) > 1 & (head_x == tail_x)) {
      tail_y <- tail_y + ((head_y - tail_y) > 0) - ((head_y - tail_y) < 0)
    } else if ((abs(head_y - tail_y) + abs(head_x - tail_x)) > 2) {
      tail_x <- tail_x + ((head_x - tail_x) > 0) - ((head_x - tail_x) < 0)
      tail_y <- tail_y + ((head_y - tail_y) > 0) - ((head_y - tail_y) < 0)
    }
    
    # Update current tail element
    head_tail_list[[i + 1]]$x <- append(head_tail_list[[i + 1]]$x, tail_x)
    head_tail_list[[i + 1]]$y <- append(head_tail_list[[i + 1]]$y, tail_y)
  }
  head_tail_list
}

input <- tibble(input = read_lines('data/2022_day09.txt')) |> 
  separate(input, into = c('dir', 'steps'), sep = ' ', convert = TRUE)
steps <- map2(input$dir, input$steps, ~rep(.x, .y)) |> unlist()

## Part A
head_tail_list <- rep(list(list(x = 0, y = 0)), 2)
head_tail_list <- reduce(steps, move_one_step, .init = head_tail_list) 
head_tail_list[[2]] |> 
  as_tibble() |> 
  unique() |> 
  nrow()

## Part B
head_tail_list <- rep(list(list(x = 0, y = 0)), 10)
head_tail_list <- reduce(steps, move_one_step, .init = head_tail_list)
head_tail_list[[10]] |>
  as_tibble() |>
  unique() |>
  nrow()
```

```{r}
tib <- head_tail_list |> 
  as_tibble() |> 
  unnest(c(head, tail)) |> 
  mutate(
    coord = rep(c('x', 'y'), each = 25),
    step = rep(c(0, seq_along(steps)), 2)
  ) |> 
  pivot_wider(names_from = 'coord', values_from = c(head, tail)) 

tib |> 
  ggplot() +
  geom_point(aes(head_x, head_y, col = 'head')) +
  geom_point(aes(tail_x, tail_y, col = 'tail')) +
  facet_wrap(vars(step))
```



```{r}
list()
```

