

```{r}
library(tidyverse)
input <- read_lines('data/2022_day02.txt')

strategy_guide <- tibble(input = input) |>
  separate(
    col = input,
    sep = ' ',
    into = c('elf', 'counter')
  ) |>
  mutate(
    counter = case_when(
      counter == 'X' ~ 'A',
      counter == 'Y' ~ 'B',
      counter == 'Z' ~ 'C'
    ),
    across(
      .fns = ~map_dbl(., ~match(.x, c('A', 'B', 'C')))
    )
  )


scores <- strategy_guide |> 
  mutate(
    score = counter + 
      ((counter == elf + 1) + 
         ((counter == 1) & (elf == 3))) * 6 +
      (counter == elf) * 3
  )

sum(scores$score)

```



```{r}
new_strategy_guide <- strategy_guide |> 
  rename(outcome = counter) |> 
  mutate(
    counter = case_when(
      outcome == 2 ~ elf,
      outcome == 3 ~ if_else(elf + 1 > 3, 1, elf + 1),
      outcome == 1 ~ if_else(elf - 1 < 1, 3, elf - 1)
    )
  ) 

new_scores <- new_strategy_guide |> 
  mutate(
    score = counter + 
      ((counter == elf + 1) + 
         ((counter == 1) & (elf == 3))) * 6 +
      (counter == elf) * 3
  )

sum(new_scores$score)

```

